name: "tfsecurity action"
description: "Runs tfsecurity and outputs any failures"
author: "info@khulnasoft.com"

inputs:
  working_directory:
    required: false
    description: |
      Directory to run the action on, from the repo root.
      Default is . (root of the repository)
    default: "."
  version:
    required: false
    description: The version of tfsecurity to use, defaults to latest
    default: latest
  format:
    required: false
    description: the format of the output
    default: default
  additional_args:
    required: false
    description: |
      Space separated args specified here will be added during tfsecurity execution.
      (eg. --force-all-dirs --verbose)
  soft_fail:
    required: false
    description: If set to `true` the action step won't break the  build
  github_token:
    description: |
      GitHub token used for making authenticated requests to the GitHub API,
      which helps avoid rate limiting
    required: false
outputs:
  tfsecurity-return-code:
    description: "tfsecurity command return code"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-pull-request"
  color: "purple"
